name: "Example Workflow"
models:
  model-1:
    key: "shxxxxxxx"
    model-class: "4o"
  model-2:
    key: "xdkfjksdjf"
    endpoint: "http://example.com/v1/"
tools:
  tool-1:
    type: "web-browser-v0.2"
    endpoint: "http://localhost:8080"
    key: "toolkey123"
trigger:
  time:
    at: "2025-03-21 22:33:33"
    repeat: "daily"
task:
  name: "Main Task"
  steps:
    - name: "step1"
      model: "model-1"
      input: "Initial input"
      output: "Output from step1"
    - name: "step2"
      tool: "tool-1"
      input: "{{task.steps.step1.output}}"
      output: "Final result"
